<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>InspectorArchivosv19</RootNamespace>
    <AssemblyName>InspectorArchivosv19</AssemblyName>
    <Version>1.0.0</Version>
    <Company>InspectorArchivosv19</Company>
    <Product>InspectorArchivosv19</Product>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  
  <ItemGroup>
    <None Include="Forms\MainForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.*" />
    <PackageReference Include="Blake3" Version="2.2.1" />
    <PackageReference Include="ClosedXML" Version="0.104.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

</Project>
